apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
        - name: consumer
          image: fahmichaabane/ctb-consumer:1.2
          resources:
            limits:
              memory: '128Mi'
              cpu: '500m'
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: consumer
spec:
  type: ClusterIP
  selector:
    app: consumer
  ports:
    - port: 3000
      targetPort: 3000
