apiVersion: apps/v1
kind: Deployment
metadata:
  name: listener
spec:
  replicas: 2
  selector:
    matchLabels:
      app: listener
  template:
    metadata:
      labels:
        app: listener
    spec:
      containers:
        - name: listener
          image: fahmichaabane/ctb-listener:1.2
          resources:
            limits:
              memory: '128Mi'
              cpu: '500m'
          ports:
            - containerPort: 3002

---
apiVersion: v1
kind: Service
metadata:
  name: listener
spec:
  type: ClusterIP
  selector:
    app: listner
  ports:
    - port: 3002
      targetPort: 3002
